diff --git a/init/Makefile b/init/Makefile
index a6d79459..bd442b10 100644
--- a/init/Makefile
+++ b/init/Makefile
@@ -12,6 +12,10 @@ obj-y += _vmm.o vmm.o
 obj-y += ld.o
 endif
 
+ifeq ($(CONFIG_KVM), y)
+obj-y += _vmm.o vmm-kvm.o
+endif
+
 ifneq ($(CONFIG_ARCH_INIT_TASK),y)
 obj-y                          += init_task.o
 endif
